// AI Tools Database - Complete Collection
const aiTools = [
    // IDE & Coding Platforms
    { name: "V0 by Vercel", category: "ide", url: "https://v0.dev", description: "Fastest way to go from idea to production-grade frontend. Generate React components with AI and deploy instantly." },
    { name: "Project IDX", category: "ide", url: "https://idx.dev", description: "Cloud IDE powered by Google with Firebase integration and Google AI. Full-stack development in the browser." },
    { name: "Cursor", category: "ide", url: "https://cursor.sh", description: "Deep repo-aware AI coding assistant. Massive productivity boost with context-aware code generation and editing." },
    { name: "Anti-Gravity", category: "ide", url: "", description: "Deep repo-aware AI coding with huge productivity jump. Advanced code understanding and generation." },
    { name: "Google AI Studio", category: "ide", url: "https://aistudio.google.com", description: "Direct access to Gemini models for serious AI development work and experimentation." },
    { name: "Together.ai", category: "ide", url: "https://together.ai", description: "Practical access to multiple open-source LLMs for development and integration." },
    { name: "Mistral AI", category: "ide", url: "https://mistral.ai", description: "Strong open models providing a reliable GPT alternative for coding tasks." },
    { name: "DeepSeek V3", category: "ide", url: "https://deepseek.com", description: "Excellent reasoning capabilities, especially optimized for coding and mathematical problems." },
    { name: "Replit", category: "ide", url: "https://replit.com", description: "Fast prototyping and deployment platform. Build and ship applications directly from your browser." },
    { name: "LLaMA Coder", category: "ide", url: "", description: "Good for quick code snippets and small tasks, less suitable for full system development." },
    { name: "21st Dev", category: "ide", url: "https://21st.dev", description: "Strong frontend productivity tool. Niche but highly useful for modern web development." },
    { name: "Acme.ai", category: "ide", url: "", description: "Quick AI app scaffolding tool. Rapid application setup and structure generation." },
    { name: "Rocket.new", category: "ide", url: "", description: "MVP-focused builder for rapid prototyping. Get your startup idea to market fast." },
    { name: "Base44", category: "ide", url: "", description: "Decent full-stack generator for complete application development." },
    { name: "GetMocha", category: "ide", url: "", description: "Startup MVP tooling focused on getting products to market quickly." },
    { name: "Emergent", category: "ide", url: "", description: "Concept-stage productivity tool for early development phases." },
    { name: "Adaptive", category: "ide", url: "", description: "Interesting AI coding tool, situational use cases for specific workflows." },
    { name: "Wegic", category: "ide", url: "", description: "Website builder with AI workflows. Automate web development tasks." },
    { name: "Macaly", category: "ide", url: "", description: "Internal-tool focused development platform for business applications." },
    { name: "Floot", category: "ide", url: "", description: "Automation-first platform with less coding depth, good for workflows." },
    { name: "Kiro", category: "ide", url: "", description: "AI coding assistant with limited ecosystem but growing capabilities." },
    { name: "I Quest Coder v1", category: "ide", url: "", description: "Early-stage AI coding tool with experimental features." },
    { name: "Same.new", category: "ide", url: "", description: "Useful for cloning existing projects, limited creativity for new builds." },
    { name: "Stitch", category: "ide", url: "", description: "UI-only productivity tool focused on interface development." },
    { name: "Jules", category: "ide", url: "", description: "Experimental AI coding assistant with innovative approaches." },
    { name: "Kimi", category: "ide", url: "", description: "Long-context AI model but region-limited availability." },
    { name: "Open Manus", category: "ide", url: "", description: "Research-heavy AI development tool for experimental projects." },
    { name: "Proxy AI", category: "ide", url: "", description: "Agent experimentation platform for AI-driven development." },
    { name: "Browser Use Web", category: "ide", url: "", description: "Advanced use cases only, specialized browser automation." },
    { name: "Trae", category: "ide", url: "", description: "Niche workflow automation for specific development tasks." },
    { name: "Deepsite", category: "ide", url: "", description: "Simple site generation tool for quick website creation." },
    { name: "GenSpark", category: "ide", url: "", description: "Research-oriented AI tool for data-heavy development." },
    { name: "Suna", category: "ide", url: "", description: "Productivity assistant, not core development tool." },
    { name: "Cluely", category: "ide", url: "", description: "Insight tool for code analysis and understanding." },
    { name: "Pinokio", category: "ide", url: "", description: "Local AI launcher for power users. Run AI models locally." },
    { name: "ChatGPT", category: "ide", url: "https://chat.openai.com", description: "AI assistant for coding help, debugging, and learning. Versatile problem-solving." },
    { name: "Perplexity AI", category: "ide", url: "https://perplexity.ai", description: "AI search engine for finding code solutions and technical documentation." },
    { name: "Owen AI", category: "ide", url: "", description: "AI coding assistant for development workflows." },
    { name: "Minimax", category: "ide", url: "", description: "AI model platform for various development tasks." },
    { name: "rork AI", category: "ide", url: "", description: "AI development tool for coding assistance." },
    { name: "FALMES.BLUE", category: "ide", url: "", description: "Development platform with AI capabilities." },
    { name: "Pydantic ORM", category: "ide", url: "https://docs.pydantic.dev", description: "Data validation library for Python using type annotations." },
    { name: "SQLAlchemy", category: "ide", url: "https://sqlalchemy.org", description: "Python SQL toolkit and Object Relational Mapper." },
    { name: "NeonDB", category: "ide", url: "https://neon.tech", description: "Serverless Postgres database with branching and instant provisioning." },
    { name: "Alembic", category: "ide", url: "https://alembic.sqlalchemy.org", description: "Database migration tool for SQLAlchemy." },
    { name: "coat.ink", category: "ide", url: "", description: "Development tool for code management." },


    // Presentation Tools
    { name: "Chronicle HQ", category: "presentation", url: "https://chronicle.app", description: "Best professional-grade slides with AI assistance. Create stunning presentations quickly." },
    { name: "Gamma", category: "presentation", url: "https://gamma.app", description: "Best balance of speed and design. AI-powered presentations that look professional instantly." },
    { name: "Beautiful.ai", category: "presentation", url: "https://beautiful.ai", description: "Clean, consistent decks with smart templates that adapt as you add content." },
    { name: "ALAI", category: "presentation", url: "", description: "Business clarity focused presentations. AI-powered slides for professional communication." },
    { name: "Gen-Spark", category: "presentation", url: "", description: "Data-heavy PPT creation. Perfect for analytics and research presentations." },
    { name: "Slides AI", category: "presentation", url: "https://slidesai.io", description: "Simple conversions from text to presentations. Quick and efficient slide generation." },
    { name: "Kiwi (Nano Banana)", category: "presentation", url: "", description: "Creative presentation tool, though output can be inconsistent." },
    { name: "Faces", category: "presentation", url: "", description: "Visual-first presentation tool with limited structure options." },

    // Video & Image Tools
    { name: "Heygen", category: "video", url: "https://heygen.com", description: "AI Video Agent specialized in avatar videos. Clone yourself and create videos in 175+ languages with lip-sync." },
    { name: "Mirage", category: "video", url: "https://mirage.ai", description: "Automated stylized editing with AI. Apply cinematic cuts, transitions, and effects instantly." },
    { name: "AVideo.com", category: "video", url: "https://avideo.com", description: "Text-to-video production with lifelike avatars. Uses NLP to break scripts into scenes." },
    { name: "Syllaby.io", category: "video", url: "https://syllaby.io", description: "Marketing and social media video creation. Generate faceless videos with scripts and subtitles." },
    { name: "Descript", category: "video", url: "https://descript.com", description: "Text-based video editing. Edit videos by editing transcripts, remove filler words with Underlord AI." },
    { name: "Synthesia", category: "video", url: "https://synthesia.io", description: "AI avatars for business. Generate studio-quality videos from text using 240+ diverse avatars in 140+ languages." },
    { name: "Riverside", category: "video", url: "https://riverside.fm", description: "All-in-one podcast and video studio with AI-powered editing and Magic Clips for highlights." },
    { name: "Wisecut", category: "video", url: "https://wisecut.video", description: "Short-form content specialist. Converts transcripts to storyboards, removes silences, finds viral clips." },
    { name: "Eddie AI", category: "video", url: "", description: "Conversational video editor. Chat-style interface to trim, reformat, and enhance videos instantly." },
    { name: "Gling.ai", category: "video", url: "https://gling.ai", description: "YouTuber-centric editor. Manages captions, noise removal, automated zooms via text commands." },
    { name: "Runway ML", category: "video", url: "https://runwayml.com", description: "AI video editing and generation. Create and edit videos with cutting-edge AI models." },
    { name: "Google Lumiere", category: "video", url: "https://lumiere.google", description: "Advanced AI video generation from Google. Create realistic video content from text." },
    { name: "Pika Labs", category: "video", url: "https://pika.art", description: "Text-to-video AI platform. Transform ideas into animated videos effortlessly." },
    { name: "Higgsfield", category: "video", url: "", description: "AI video generation with advanced features for creative content." },
    { name: "Pictory AI", category: "video", url: "https://pictory.ai", description: "Turn scripts and articles into engaging videos automatically." },
    { name: "AutoTae", category: "video", url: "", description: "Automated video editing with AI-powered features." },
    { name: "Step Video T2V", category: "video", url: "", description: "Text-to-video generation with step-by-step control." },
    { name: "Wan 2.6", category: "video", url: "", description: "Advanced video generation model with high-quality output." },
    { name: "Wan 2.1", category: "video", url: "", description: "Video generation AI with creative capabilities." },
    { name: "Midjourney", category: "video", url: "https://midjourney.com", description: "AI image generation at its finest. Create stunning, artistic images from text descriptions." },
    { name: "Imagen 3", category: "video", url: "", description: "Google's advanced image generation model with photorealistic output." },
    { name: "Leonardo AI", category: "video", url: "https://leonardo.ai", description: "AI image generation with fine control. Perfect for game assets, concept art, and design." },
    { name: "Nano Banana", category: "video", url: "", description: "Creative AI image generation tool with unique style." },
    { name: "Google Whisk", category: "video", url: "", description: "Google's experimental image generation and editing tool." },
    { name: "StockIMG", category: "video", url: "", description: "AI-generated stock images for commercial use." },
    { name: "MagicQuill", category: "video", url: "", description: "AI-powered image editing with intelligent brush tools." },
    { name: "Seedream", category: "video", url: "", description: "Dream-like AI image generation with artistic styles." },
    { name: "Hunyuan 3D", category: "video", url: "", description: "3D model generation from text or images." },
    { name: "NVIDIA Shutterstock 3D", category: "video", url: "", description: "Professional 3D asset generation powered by NVIDIA." },
    { name: "ElevenLabs", category: "video", url: "https://elevenlabs.io", description: "AI voice generation and cloning. Create natural-sounding voiceovers in any voice." },
    { name: "Retell AI", category: "video", url: "", description: "AI voice conversation platform for interactive experiences." },
    { name: "VAPI", category: "video", url: "", description: "Voice AI platform for building conversational applications." },
    { name: "Natural Reader", category: "video", url: "https://naturalreader.com", description: "Text-to-speech with natural-sounding voices for accessibility." },
    { name: "Omnidim AI", category: "video", url: "", description: "Multi-dimensional AI voice and audio generation." },
    { name: "Speechma", category: "video", url: "", description: "Speech synthesis and voice cloning platform." },
    { name: "Minimax Audio", category: "video", url: "", description: "Advanced audio generation with AI models." },

    // Productivity Tools
    { name: "Notion AI", category: "productivity", url: "https://notion.so", description: "All-in-one workspace with AI. Summarize, rewrite, and organize content intelligently." },
    { name: "Notebook LLM", category: "productivity", url: "https://notebooklm.google", description: "Massive boost for learning from PDFs. AI-powered research and note-taking assistant." },
    { name: "Elicit", category: "productivity", url: "https://elicit.org", description: "Research-grade academic productivity. Automate literature reviews and research tasks." },
    { name: "STORM", category: "productivity", url: "", description: "Structured reports with citations. AI-powered research paper generation." },
    { name: "Glasp", category: "productivity", url: "https://glasp.co", description: "Best bookmarking and highlighting tool. Organize and share your learning journey." },
    { name: "X-Mind AI", category: "productivity", url: "", description: "Visual thinking from documents. Mind mapping with AI assistance." },
    { name: "AskYourPDF", category: "productivity", url: "https://askyourpdf.com", description: "Chat with your PDF documents. Extract insights and answers instantly." },
    { name: "Memex", category: "productivity", url: "", description: "Personal knowledge management with AI-powered search and organization." },
    { name: "Reflect", category: "productivity", url: "https://reflect.app", description: "Note-taking with AI-powered backlinks and networked thought." },
    { name: "Tactiq AI", category: "productivity", url: "https://tactiq.io", description: "Meeting transcription and AI summaries for video calls." },
    { name: "Infography", category: "productivity", url: "", description: "Transform data into visual infographics with AI." },
    { name: "Graphy", category: "productivity", url: "", description: "Data visualization and chart creation with AI assistance." },
    { name: "Musely", category: "productivity", url: "", description: "Creative productivity tool for content organization." },
    { name: "Grammarly", category: "productivity", url: "https://grammarly.com", description: "AI-powered grammar and writing assistant. Improve clarity, tone, and correctness." },
    { name: "Loom", category: "productivity", url: "https://loom.com", description: "Quick video messaging for teams. Record and share screen recordings instantly." },
    { name: "Trello", category: "productivity", url: "https://trello.com", description: "Task boards for project management. Visual organization with AI suggestions." },
    { name: "Todoist", category: "productivity", url: "https://todoist.com", description: "Task manager with AI-powered scheduling and prioritization." },
    { name: "RescueTime", category: "productivity", url: "https://rescuetime.com", description: "Track time and focus with AI insights into your productivity patterns." },
    { name: "Clockify", category: "productivity", url: "https://clockify.me", description: "Free time tracker for teams and individuals." },
    { name: "Pomofocus", category: "productivity", url: "https://pomofocus.io", description: "Pomodoro timer for focused work sessions." },
    { name: "Miro", category: "productivity", url: "https://miro.com", description: "Whiteboard collaboration with AI-powered brainstorming." },
    { name: "Google Keep", category: "productivity", url: "https://keep.google.com", description: "Simple notes and reminders synced across devices." },
    { name: "Evernote", category: "productivity", url: "https://evernote.com", description: "Note-taking app with powerful organization and search." },
    { name: "Scribehow", category: "productivity", url: "https://scribehow.com", description: "Auto documentation tool. Create step-by-step guides automatically." },

    // Automation Tools
    { name: "Zapier", category: "automation", url: "https://zapier.com", description: "Connect 6,000+ apps with AI-powered automation. No-code workflow builder." },
    { name: "Make", category: "automation", url: "https://make.com", description: "Visual drag-and-drop automation platform with built-in AI modules for complex workflows." },
    { name: "n8n", category: "automation", url: "https://n8n.io", description: "Open-source, self-hosted automation alternative. Full control over your workflows." },
    { name: "Pipedream", category: "automation", url: "https://pipedream.com", description: "Developer-friendly automation with OpenAI and LangChain integrations." },
    { name: "Apollo.io", category: "automation", url: "https://apollo.io", description: "AI-driven prospecting to automate outbound sales sequences at scale." },
    { name: "Clay", category: "automation", url: "https://clay.com", description: "Data enrichment platform for hyper-personalized outreach automation." },
    { name: "Lavender AI", category: "automation", url: "https://lavender.ai", description: "Real-time writing assistant for crafting high-performing cold emails." },
    { name: "Magical AI", category: "automation", url: "https://magical.so", description: "Automates repetitive sales tasks to boost efficiency." },
    { name: "Polymer Search", category: "automation", url: "https://polymersearch.com", description: "Instantly transforms spreadsheets into interactive AI dashboards." },
    { name: "DashThis", category: "automation", url: "https://dashthis.com", description: "Automates marketing data visualization and insights." },
    { name: "MonkeyLearn", category: "automation", url: "https://monkeylearn.com", description: "Uses AI for text analysis and automated dashboard creation." },
    { name: "SheetAI", category: "automation", url: "", description: "Brings GPT-powered intelligence directly into Google Sheets." },
    { name: "Maken", category: "automation", url: "", description: "AI agent automation for complex workflows." },
    { name: "Apify", category: "automation", url: "https://apify.com", description: "Web scraping and automation platform with AI capabilities." },
    { name: "Hugging Face", category: "automation", url: "https://huggingface.co", description: "ML model hub and deployment platform for AI automation." },
    { name: "MindPal", category: "automation", url: "", description: "AI-powered workflow automation for knowledge work." },
    { name: "Airtable", category: "automation", url: "https://airtable.com", description: "Database and workflow automation with AI integrations." },
    { name: "ManyChat", category: "automation", url: "https://manychat.com", description: "Chatbot automation for marketing and customer engagement." },
    { name: "Gemini Gems", category: "automation", url: "", description: "Custom AI agents built on Google's Gemini platform." },

    // Content Creation
    { name: "Jasper AI", category: "content", url: "https://jasper.ai", description: "Multi-step AI workflows for teams producing content at scale. Marketing copy and blog posts." },
    { name: "Copy.ai", category: "content", url: "https://copy.ai", description: "AI copywriting tool. Automate marketing campaigns with GPT-powered workflows." },
    { name: "Outranking", category: "content", url: "https://outranking.io", description: "AI-powered SEO platform for creating high-ranking blog content with optimization." },
    { name: "Murf AI", category: "content", url: "https://murf.ai", description: "AI voiceovers for videos and presentations. Studio-quality voice generation." },
    { name: "Quillbot", category: "content", url: "https://quillbot.com", description: "Paraphrasing and rewriting tool. Improve your writing with AI suggestions." },
    { name: "Hemingway App", category: "content", url: "https://hemingwayapp.com", description: "Writing clarity tool. Makes your writing bold and clear." },
    { name: "ProWritingAid", category: "content", url: "https://prowritingaid.com", description: "Writing improvement tool with style suggestions and grammar checking." },
    { name: "Wordtune", category: "content", url: "https://wordtune.com", description: "Rewrite sentences for clarity and impact with AI suggestions." },
    { name: "Readsy", category: "content", url: "https://readsy.co", description: "Speed reading tool to consume content faster." },
    { name: "Airstory", category: "content", url: "https://airstory.co", description: "Content research and writing platform for organized creation." },
    { name: "Cliche Finder", category: "content", url: "", description: "Remove clichés from your writing for more original content." },
    { name: "Durable", category: "content", url: "https://durable.co", description: "AI website builder that creates complete sites in seconds." },

    // Marketing Tools
    { name: "HubSpot", category: "marketing", url: "https://hubspot.com", description: "Marketing guides and CRM with AI-powered insights. Complete marketing automation." },
    { name: "Buffer", category: "marketing", url: "https://buffer.com", description: "Social media scheduling with AI recommendations. Plan and publish content efficiently." },
    { name: "Hootsuite", category: "marketing", url: "https://hootsuite.com", description: "Social media management platform. Schedule, monitor, and analyze social content." },
    { name: "Mailchimp", category: "marketing", url: "https://mailchimp.com", description: "Email marketing with AI optimization. Create campaigns that convert." },
    { name: "Sender AI", category: "marketing", url: "https://sender.net", description: "Automate personalized email and SMS campaigns with AI targeting." },
    { name: "Customer.io", category: "marketing", url: "https://customer.io", description: "Behavioral targeting using event-driven marketing automation." },
    { name: "Ortto", category: "marketing", url: "https://ortto.com", description: "Combines customer data with GPT-powered content creation." },
    { name: "Brevo", category: "marketing", url: "https://brevo.com", description: "AI-powered CRM automation for small to mid-sized businesses." },
    { name: "Ubersuggest", category: "marketing", url: "https://ubersuggest.com", description: "SEO tool for keyword research and content ideas." },
    { name: "AnswerThePublic", category: "marketing", url: "https://answerthepublic.com", description: "Keyword ideas based on real search queries." },
    { name: "Buzzsumo", category: "marketing", url: "https://buzzsumo.com", description: "Content research tool to find trending topics and influencers." },
    { name: "Bitly", category: "marketing", url: "https://bitly.com", description: "URL shortener with analytics for link tracking." },
    { name: "Google Trends", category: "marketing", url: "https://trends.google.com", description: "Trending topics and search insights for content planning." },
    { name: "CanIRank", category: "marketing", url: "https://canirank.com", description: "SEO content ranking and optimization recommendations." },
    { name: "Tidio AI", category: "marketing", url: "https://tidio.com", description: "Chatbots with intent detection for smarter customer conversations." },
    { name: "Intercom Fin AI", category: "marketing", url: "https://intercom.com", description: "Resolves over 50% of support tickets automatically with AI." },
    { name: "Drift", category: "marketing", url: "https://drift.com", description: "B2B AI platform with meeting scheduling and sales integrations." },
    { name: "Botpress", category: "marketing", url: "https://botpress.com", description: "Open-source platform for building advanced AI chatbots." },

    // Design Tools
    { name: "Figma", category: "design", url: "https://figma.com", description: "UI/UX design tool with AI plugins. Collaborative design platform for teams." },
    { name: "Canva", category: "design", url: "https://canva.com", description: "Easy design for everyone with AI-powered templates and Magic Design features." },
    { name: "Spline", category: "design", url: "https://spline.design", description: "3D design tool for the web. Create interactive 3D experiences easily." },
    { name: "Remove.bg", category: "design", url: "https://remove.bg", description: "AI-powered background removal. Clean image backgrounds in seconds." },
    { name: "Coolors", category: "design", url: "https://coolors.co", description: "Color palette generator with AI suggestions. Create beautiful color schemes." },
    { name: "Unsplash", category: "design", url: "https://unsplash.com", description: "Free high-quality stock images. Millions of photos for your projects." },
    { name: "Flaticon", category: "design", url: "https://flaticon.com", description: "Free icons for your design projects. Millions of vector icons." },
    { name: "Dribbble", category: "design", url: "https://dribbble.com", description: "Design inspiration and portfolio showcase platform." },
    { name: "Behance", category: "design", url: "https://behance.net", description: "Creative portfolios and project showcase from Adobe." },
    { name: "Unscreen", category: "design", url: "https://unscreen.com", description: "Remove video backgrounds automatically with AI." },
    { name: "U18.net", category: "design", url: "", description: "Premium design assets and resources." },
    { name: "Reactbits", category: "design", url: "", description: "React component library for modern web design." },
    { name: "Unicorn Studio", category: "design", url: "", description: "WebGL-based animation and interaction design tool." },
    { name: "Effecto", category: "design", url: "", description: "Visual effects and animation for web design." },
    { name: "Paper Designs", category: "design", url: "", description: "Paper-style design elements and templates." },
    { name: "Shaderfog", category: "design", url: "", description: "Shader-based visual effects for web." },
    { name: "Peachweb", category: "design", url: "", description: "Modern web design templates and components." },
    { name: "shadcn/ui", category: "design", url: "https://ui.shadcn.com", description: "Beautifully designed components built with Radix UI and Tailwind." },
    { name: "100l5", category: "design", url: "", description: "Design system and component library." },
    { name: "uiverse.io", category: "design", url: "https://uiverse.io", description: "Open-source UI elements made with CSS and HTML." },
    { name: "60fps.design", category: "design", url: "", description: "High-performance web animations and interactions." },
    { name: "Fontjoy", category: "design", url: "https://fontjoy.com", description: "Generate font pairings with AI." },
    { name: "Lump.ai", category: "design", url: "", description: "AI-powered design asset generation." },
    { name: "Mobbin", category: "design", url: "https://mobbin.com", description: "Mobile and web design inspiration library." },
    { name: "Awwwards", category: "design", url: "https://awwwards.com", description: "Best web design trends and awards." },
    { name: "Anime.js", category: "design", url: "https://animejs.com", description: "Lightweight JavaScript animation library." },
    { name: "CSS Grid Generator", category: "design", url: "", description: "Visual tool for creating CSS Grid layouts." },
    { name: "Animista", category: "design", url: "https://animista.net", description: "CSS animation library and generator." },
    { name: "CSS Gradient", category: "design", url: "https://cssgradient.io", description: "CSS gradient generator with visual editor." },
    { name: "Supaherogo", category: "design", url: "", description: "Hero section design templates and inspiration." },
    { name: "FPS Designs", category: "design", url: "", description: "High-performance design patterns." },
    { name: "Seesaw", category: "design", url: "", description: "Interactive design components." },
    { name: "Adfolio", category: "design", url: "", description: "Portfolio templates for creatives." },
    { name: "Typefaces.today", category: "design", url: "", description: "Modern typeface showcase and discovery." },
    { name: "Jector.ai", category: "design", url: "", description: "AI-powered design projection and mockups." },
    { name: "Pushkeen.ai", category: "design", url: "", description: "AI design assistant for creative work." },
    { name: "Sneakpeak.design", category: "design", url: "", description: "Design preview and feedback tool." },
    { name: "Colonise.ai", category: "design", url: "", description: "AI-powered design system generation." },
    { name: "Apply.app", category: "design", url: "", description: "Design application templates." },
    { name: "3dwebsite.design", category: "design", url: "", description: "3D website design inspiration and tools." },
    { name: "Codewithrandom", category: "design", url: "", description: "Random design and code inspiration." },
    { name: "MagicUI", category: "design", url: "", description: "Magical UI components and animations." },
    { name: "Headers.club", category: "design", url: "", description: "Header design inspiration and templates." },
    { name: "Recentwork.com", category: "design", url: "", description: "Recent design work showcase." },
    { name: "Vibe Designing", category: "design", url: "", description: "Mood-based design inspiration." },
    { name: "uxmagic.ai", category: "design", url: "", description: "AI-powered UX design suggestions." },
    { name: "Uizard", category: "design", url: "https://uizard.io", description: "AI-powered UI design from screenshots and sketches." },
    { name: "Napkin AI", category: "design", url: "", description: "Turn text into visual diagrams with AI." },
    { name: "ToolFK", category: "design", url: "", description: "Design tool collection and resources." },
    { name: "IMAGE.PI", category: "design", url: "", description: "AI image processing and enhancement." },
    { name: "WhiteScreen.online", category: "design", url: "", description: "Screen testing and calibration tool." },
    { name: "Visually.net", category: "design", url: "", description: "Visual content creation platform." },
    { name: "Grainiest.supply", category: "design", url: "", description: "Grainy texture and design resources for modern web design." },
    { name: "csvistool.com", category: "design", url: "", description: "CSV data visualization tool." },

    // Learning & Education
    { name: "FreeCodeCamp", category: "learning", url: "https://freecodecamp.org", description: "Learn to code for free with interactive tutorials and projects." },
    { name: "W3Schools", category: "learning", url: "https://w3schools.com", description: "Easy coding tutorials and references for web development." },
    { name: "Codecademy", category: "learning", url: "https://codecademy.com", description: "Interactive coding lessons for various programming languages." },
    { name: "Codehype.in", category: "learning", url: "https://codehype.in", description: "Free learning resources for developers." },
    { name: "GeeksforGeeks", category: "learning", url: "https://geeksforgeeks.org", description: "Coding tutorials, algorithms, and interview preparation." },
    { name: "CS50 Harvard", category: "learning", url: "https://cs50.harvard.edu", description: "Free coding course from Harvard University." },
    { name: "LeetCode", category: "learning", url: "https://leetcode.com", description: "DSA practice and coding interview preparation." },
    { name: "Exercism", category: "learning", url: "https://exercism.org", description: "Hands-on coding exercises with mentor feedback." },
    { name: "Sololearn", category: "learning", url: "https://sololearn.com", description: "Beginner-friendly mobile learning for coding." },
    { name: "Programiz", category: "learning", url: "https://programiz.com", description: "Beginner-friendly programming guides and tutorials." },
    { name: "Coursera", category: "learning", url: "https://coursera.org", description: "University courses and professional certificates online." },
    { name: "Skillshare", category: "learning", url: "https://skillshare.com", description: "Skill-based learning for creative and technical topics." },
    { name: "Khan Academy", category: "learning", url: "https://khanacademy.org", description: "Free courses on various subjects including programming." },
    { name: "MindTools", category: "learning", url: "https://mindtools.com", description: "Career skills and professional development resources." },
    { name: "TED", category: "learning", url: "https://ted.com", description: "Inspiring talks and ideas from experts worldwide." },
    { name: "Duolingo", category: "learning", url: "https://duolingo.com", description: "Language learning with gamification and AI." },
    { name: "Udemy", category: "learning", url: "https://udemy.com", description: "Affordable online courses on thousands of topics." },
    { name: "FutureLearn", category: "learning", url: "https://futurelearn.com", description: "Free short courses from top universities." },
    { name: "Brilliant", category: "learning", url: "https://brilliant.org", description: "Problem-solving and STEM learning through interactive lessons." },
    { name: "EdX", category: "learning", url: "https://edx.org", description: "University-level courses from MIT, Harvard, and more." },
    { name: "LinkedIn Learning", category: "learning", url: "https://linkedin.com/learning", description: "Professional development courses for career growth." },
    { name: "Indeed", category: "learning", url: "https://indeed.com", description: "Job search engine with career resources." },
    { name: "Glassdoor", category: "learning", url: "https://glassdoor.com", description: "Company reviews, salaries, and job listings." },
    { name: "Internshala", category: "learning", url: "https://internshala.com", description: "Internships and entry-level jobs in India." },
    { name: "AngelList", category: "learning", url: "https://angel.co", description: "Startup jobs and investment opportunities." },
    { name: "Naukri", category: "learning", url: "https://naukri.com", description: "Leading Indian job portal for all industries." },
    { name: "Wellfound", category: "learning", url: "https://wellfound.com", description: "Tech startup hiring and job search." },
    { name: "FlexJobs", category: "learning", url: "https://flexjobs.com", description: "Remote and flexible job opportunities." },
    { name: "Levels.fyi", category: "learning", url: "https://levels.fyi", description: "Salary data and career levels for tech companies." },
    { name: "Jobscan", category: "learning", url: "https://jobscan.co", description: "Resume optimization for ATS systems." },
    { name: "Investopedia", category: "learning", url: "https://investopedia.com", description: "Finance education and investment learning." },

    // Deployment & Infrastructure
    { name: "Vercel", category: "deployment", url: "https://vercel.com", description: "Frontend deployment platform with instant global CDN." },
    { name: "Netlify", category: "deployment", url: "https://netlify.com", description: "Modern web deployment with continuous deployment from Git." },
    { name: "Firebase", category: "deployment", url: "https://firebase.google.com", description: "Google's app development platform with hosting and backend services." },
    { name: "Render", category: "deployment", url: "https://render.com", description: "Cloud platform for deploying web apps, APIs, and databases." },
    { name: "Railway", category: "deployment", url: "https://railway.app", description: "Infrastructure platform with simple deployment from Git." },
    { name: "Fly.io", category: "deployment", url: "https://fly.io", description: "Deploy apps globally with edge computing capabilities." },
    { name: "OpenRouter", category: "deployment", url: "https://openrouter.ai", description: "Unified API for accessing multiple LLM models." },
    { name: "GroqCloud", category: "deployment", url: "https://groq.com", description: "Ultra-fast LLM inference with specialized hardware." },
    { name: "Relevance AI", category: "deployment", url: "https://relevanceai.com", description: "Build and deploy AI agents and workflows." },
    { name: "Google Skills", category: "deployment", url: "", description: "Google's platform for skill development and certification." },

    // APIs & Developer Tools
    { name: "OpenWeather API", category: "api", url: "https://openweathermap.org/api", description: "Weather data API for current and forecast information." },
    { name: "Unsplash API", category: "api", url: "https://unsplash.com/developers", description: "Free high-quality images API for applications." },
    { name: "JSONPlaceholder", category: "api", url: "https://jsonplaceholder.typicode.com", description: "Free fake REST API for testing and prototyping." },
    { name: "ReqRes", category: "api", url: "https://reqres.in", description: "Hosted REST API for testing HTTP requests." },
    { name: "News API", category: "api", url: "https://newsapi.org", description: "Live news headlines and articles from sources worldwide." },
    { name: "REST Countries API", category: "api", url: "https://restcountries.com", description: "Country data including flags, currencies, and languages." },
    { name: "RandomUser.me", category: "api", url: "https://randomuser.me", description: "Generate random user data for testing." },
    { name: "CoinGecko API", category: "api", url: "https://coingecko.com/api", description: "Cryptocurrency prices and market data." },
    { name: "NASA Open APIs", category: "api", url: "https://api.nasa.gov", description: "Access NASA data including astronomy pictures and Mars rover photos." },
    { name: "OpenStreetMap API", category: "api", url: "https://openstreetmap.org/api", description: "Free geographic data and mapping API." },
    { name: "YouTube Data API", category: "api", url: "https://developers.google.com/youtube", description: "Access YouTube videos, channels, and playlists data." },
    { name: "Spotify API", category: "api", url: "https://developer.spotify.com", description: "Music data and playback control API." },
    { name: "PokeAPI", category: "api", url: "https://pokeapi.co", description: "Pokemon data API with comprehensive information." },
    { name: "Giphy API", category: "api", url: "https://developers.giphy.com", description: "GIF search and integration API." },
    { name: "IPify API", category: "api", url: "https://ipify.org", description: "Simple public IP address API." },
    { name: "IP Geolocation API", category: "api", url: "", description: "Get location data from IP addresses." },
    { name: "MealDB API", category: "api", url: "https://themealdb.com/api.php", description: "Recipe and meal information database." },
    { name: "Universities API", category: "api", url: "", description: "Search universities worldwide with detailed information." },
    { name: "Trivia API", category: "api", url: "", description: "Trivia questions for quiz applications." },
    { name: "Fun Translation API", category: "api", url: "", description: "Translate text into fun languages like Yoda or Pirate." },
    { name: "Bored API", category: "api", url: "https://boredapi.com", description: "Random activity suggestions to fight boredom." },
    { name: "Numbers API", category: "api", url: "http://numbersapi.com", description: "Interesting facts about numbers." },
    { name: "Dog CEO API", category: "api", url: "https://dog.ceo/dog-api", description: "Random dog images by breed." },
    { name: "Cat API", category: "api", url: "https://thecatapi.com", description: "Random cat images and breed information." },
    { name: "Genderize.io", category: "api", url: "https://genderize.io", description: "Predict gender from first name." },
    { name: "TinyURL", category: "api", url: "https://tinyurl.com", description: "URL shortening service with API." },
    { name: "PDFescape", category: "api", url: "https://pdfescape.com", description: "Edit PDFs online without software." },
    { name: "CloudConvert", category: "api", url: "https://cloudconvert.com", description: "File conversion API supporting 200+ formats." },
    { name: "WeTransfer", category: "api", url: "https://wetransfer.com", description: "Send large files up to 2GB for free." },
    { name: "SmallPDF", category: "api", url: "https://smallpdf.com", description: "PDF tools for compression, conversion, and editing." },
    { name: "TempMail", category: "api", url: "https://tempmail.org", description: "Temporary email addresses for privacy." },
    { name: "ShareX", category: "api", url: "https://getsharex.com", description: "Screen capture and file sharing tool." },
    { name: "Wayback Machine", category: "api", url: "https://archive.org/web", description: "Browse archived versions of websites." },
    { name: "TradingView", category: "api", url: "https://tradingview.com", description: "Stock charts and financial market analysis." },
    { name: "MoneyControl", category: "api", url: "https://moneycontrol.com", description: "Finance news and market data for India." },
    { name: "Mint", category: "api", url: "https://mint.com", description: "Personal finance tracker and budgeting tool." },
    { name: "YNAB", category: "api", url: "https://youneedabudget.com", description: "Budget planning and financial management." },
    { name: "CoinMarketCap", category: "api", url: "https://coinmarketcap.com", description: "Cryptocurrency prices and market capitalization." },
    { name: "Cleartax", category: "api", url: "https://cleartax.in", description: "Tax filing and financial planning for India." },
    { name: "Groww", category: "api", url: "https://groww.in", description: "Investment app for stocks and mutual funds in India." },
    { name: "PayPal", category: "api", url: "https://paypal.com", description: "Online payment processing and money transfers." },
    { name: "Wise", category: "api", url: "https://wise.com", description: "International money transfers with low fees." }
];

// Initialize localStorage with all tools
// This will update localStorage with the latest tools from this file
localStorage.setItem('aiTools', JSON.stringify(aiTools));
